### ISSUE TITLE
Bug：GroupID type error when in sql

### ISSUE THREAD

**Issue by hanson-wen** [openimsdk/open-im-sdk-web-wasm#75]
### What happened?

just as the picture show below, the groupID is string ,but sql combine as int type.

![image](https://github.com/openimsdk/open-im-sdk-web-wasm/assets/25191019/eec4dbab-90c9-40b0-9c48-1b3891ff977b)

![image](https://github.com/openimsdk/open-im-sdk-web-wasm/assets/25191019/af09d640-a2a5-48c1-8002-e2bb0afb523c)

### What did you expect to happen?

it may be select  xxxxx where xxxx   in('aaa', 'bbbb')

### How can we reproduce it (as minimally and precisely as possible)?

return a groupID as string

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by Bloomingg** [comment]
fixed with there commits [fix: allow some id as string](https://github.com/openimsdk/open-im-sdk-web-wasm/commit/e0bcc7e6fa7fdd69fed35e03c30c3d8d10387d4f), [fix: allow conversation id as string with symbol](https://github.com/openimsdk/open-im-sdk-web-wasm/commit/9e8df60979d706bf50681596d5a04c40be2100bb).
and and release with open-im-sdk-wasm@3.5.1-alpha.8.1.
